[listen]
# TCP и UDP адресы, которые слушает прокси
# допускается 0.0.0.0:port или :port
# при необходимости можно разделить порты
 tcp = ":25565"
 udp = ":25565"

[backend]
# адрес Velocity/Backend сервера
 tcp = "127.0.0.1:25565"
 udp = "127.0.0.1:25565"

# таймаут неактивности ассоциаций UDP в секундах
idle_timeout_seconds = 300 